// Generated by `gridlock contract export`. Do not edit manually.

export interface Bounds {
  west: number;
  south: number;
  east: number;
  north: number;
}
export interface ConstructionWindow {
  startDate: string;
  endDate: string;
}
export interface DateRange {
  start: string | null;
  end: string | null;
}
export interface Endpoint {
  name: string;
  role: EndpointRole;
  qualifiers: Array<string>;
}
export interface EndpointMatch {
  endpoint: string;
  role: EndpointRole;
  status: EndpointMatchStatus;
  featureId: string | null;
  featureName: string | null;
  operator: string | null;
  operatorRelation: string | null;
  voltageKv: Array<number>;
  nameScore: number | null;
  point: Point | null;
  notes: Array<string>;
}
export type EndpointMatchStatus = "matched" | "override" | "no_candidate" | "ambiguous" | "vetoed" | "separation_rejected";
export type EndpointRole = "from" | "to" | "via" | "single" | "unknown";
export type EndpointStatus = "explicit_pair" | "chain" | "single_site" | "none";
export interface Evidence {
  level: EvidenceLevel;
  score: number;
  breakdown: Record<string, number>;
  reasons: Array<string>;
  warnings: Array<string>;
}
export type EvidenceLevel = "HIGH" | "MEDIUM" | "LOW" | "UNRESOLVED";
export type GeometryMethod = "verified_full_line" | "verified_endpoints_straight_line" | "verified_endpoint_route" | "verified_single_endpoint" | "approximate_area_centroid" | "human_verified_override" | "unresolved";
export interface GeometryResolution {
  method: GeometryMethod;
  isApproximation: boolean;
  featureIds: Array<string>;
  matches: Array<EndpointMatch>;
  warnings: Array<string>;
}
export interface ImpactAssumption {
  id: string;
  title: string;
  label: string;
  low: number | null;
  high: number;
  unit: string;
  value: string;
  basis: string;
  sourceTitle: string;
  sourceUrl: string | null;
  sourceLocator: string;
  caveat: string;
  approvedBy: string;
  approvedOn: string;
}
export interface ImpactChainStep {
  label: string;
  value: string;
  detail: string | null;
  assumptionIds: Array<string>;
}
export interface ImpactCluster {
  kind: string;
  projectIds: Array<string>;
  relationshipIds: Array<string>;
  costedProjectIds: Array<string>;
  uncostedProjectIds: Array<string>;
  publishedCostUsd: number;
  avoidableShare: number;
}
export interface ImpactIndicator {
  summary: string;
  detail: string;
}
export interface ImpactRange {
  low: number | null;
  high: number;
}
export type ImpactStatus = "ESTIMATED" | "NOT_ESTIMATED";
export interface ImpactStep {
  label: string;
  working: string;
  assumptionIds: Array<string>;
}
export interface Metadata {
  schemaVersion: string;
  fixture: boolean;
  distanceUnit: string;
  thresholdsKm: Record<string, number>;
  timelineGapDays: Record<string, number>;
  zoneGuards: Record<string, unknown>;
  utilityColors: Record<string, string>;
  utilityNames: Record<string, string>;
  labels: Record<string, Record<string, string>>;
  sources: Array<SourceSnapshot>;
  impactAssumptions: Array<ImpactAssumption>;
}
export interface Metrics {
  projects: number;
  projectsByUtility: Record<string, number>;
  locatedProjects: number;
  notAssessedByUtility: Record<string, number>;
  resolution: ResolutionBreakdown;
  resolutionByUtility: Record<string, ResolutionBreakdown>;
  projectsWithNamedEndpoints: number;
  automaticResolutionRate: number;
  humanVerifiedEndpoints: number;
  relationships: number;
  relationshipsByTier: Record<string, number>;
  zones: number;
  attentionCompressionRatio: number | null;
  evidenceDistribution: Record<string, number>;
  geometryDistribution: Record<string, number>;
}
export interface Point {
  lat: number;
  lon: number;
}
export type Priority = "HIGH" | "MEDIUM" | "LOW";
export interface Project {
  id: string;
  utility: string;
  projectName: string;
  projectType: ProjectType;
  sponsor: string | null;
  description: string | null;
  voltageKv: Array<number>;
  endpoints: Array<Endpoint>;
  endpointStatus: EndpointStatus;
  status: string | null;
  plannedInServiceDate: string | null;
  filedStartDate: string | null;
  constructionWindow: ConstructionWindow | null;
  estimatedCostUsd: number | null;
  source: SourceRef;
  geometry: Record<string, unknown> | null;
  geometryResolution: GeometryResolution | null;
  evidence: Evidence | null;
  warnings: Array<string>;
}
export type ProjectType = "transmission_line" | "substation" | "reactor" | "other";
export interface Relationship {
  id: string;
  projectA: string;
  projectB: string;
  distanceKm: number;
  closestPoints: [Point, Point];
  spatialTier: SpatialTier;
  geometryMethods: [GeometryMethod, GeometryMethod];
  approximate: boolean;
  timeline: Timeline;
  opportunityPriority: Priority | null;
  rank: number | null;
  coordinationPlaybook: Array<string>;
  evidence: Evidence;
}
export interface ResolutionBreakdown {
  locatedAutomatically: number;
  locatedHumanVerifiedOnly: number;
  notLocatedUnresolved: number;
  notLocatedNoNamedSite: number;
}
export interface SourceRef {
  document: string;
  projectIdRaw: string;
  page: number;
  rawText: string | null;
  rawFields: Record<string, string>;
}
export interface SourceSnapshot {
  kind: string;
  name: string;
  retrievedAt: string | null;
  sha256: string | null;
}
export type SpatialTier = "CROSSING" | "SHARED_CORRIDOR" | "SITE_LOGISTICS" | "CREWS_EQUIPMENT";
export interface Timeline {
  type: TimelineType;
  gapDays: number | null;
  overlapDays: number | null;
  relevance: TimelineRelevance;
  isdWithinFiledSpan: boolean;
}
export type TimelineRelevance = "OVERLAPPING" | "STRONG" | "MEANINGFUL" | "POSSIBLE" | "WEAK" | "UNKNOWN";
export type TimelineType = "IN_SERVICE_GAP" | "WINDOW_OVERLAP" | "WINDOW_GAP" | "UNRESOLVED";
export interface Zone {
  id: string;
  rank: number | null;
  name: string;
  projectIds: Array<string>;
  relationshipIds: Array<string>;
  topRelationshipId: string | null;
  headline: ZoneHeadline | null;
  utilities: Array<string>;
  closestDistanceKm: number;
  inServiceRange: DateRange;
  geographicSpanKm: number | null;
  timelineSpanDays: number | null;
  opportunityPriority: Priority;
  evidenceLevel: EvidenceLevel;
  coordinationThemes: Array<string>;
  bounds: Bounds;
  warnings: Array<string>;
}
export interface ZoneHeadline {
  relationshipId: string;
  projectA: string;
  projectB: string;
  distanceKm: number;
  spatialTier: SpatialTier;
  timelineType: TimelineType;
  gapDays: number | null;
  timelineRelevance: TimelineRelevance;
  opportunityPriority: Priority;
}
export interface ZoneImpact {
  zoneId: string;
  status: ImpactStatus;
  label: string;
  reason: string | null;
  themes: Array<string>;
  stagingYards: ImpactRange | null;
  temporaryAcres: ImpactRange | null;
  mobilizations: ImpactRange | null;
  budgetInPlayUsd: ImpactRange | null;
  expectedSavingUsd: ImpactRange | null;
  clusters: Array<ImpactCluster>;
  steps: Array<ImpactStep>;
  notes: Array<string>;
  relationshipCount: number;
  candidateCount: number;
  timelyCount: number;
  chain: Array<ImpactChainStep>;
  indicators: Array<ImpactIndicator>;
}
export interface Payload {
  metadata: Metadata;
  metrics: Metrics | null;
  projects: Array<Project>;
  relationships: Array<Relationship>;
  zones: Array<Zone>;
  impact: Array<ZoneImpact>;
}

export type GridlockPayload = Payload;
