// Generated by `gridlock contract export`. Do not edit manually.

export interface Bounds {
  west: number;
  south: number;
  east: number;
  north: number;
}
export interface ConstructionWindow {
  startDate: string;
  endDate: string;
}
export interface Endpoint {
  name: string;
  role?: EndpointRole;
  qualifiers?: Array<string>;
}
export type EndpointRole = "from" | "to" | "via" | "single" | "unknown";
export type EndpointStatus = "explicit_pair" | "chain" | "single_site" | "none";
export interface Evidence {
  level: EvidenceLevel;
  score: number;
  reasons?: Array<string>;
  warnings?: Array<string>;
}
export type EvidenceLevel = "HIGH" | "MEDIUM" | "LOW" | "UNRESOLVED";
export type GeometryMethod = "verified_full_line" | "verified_endpoints_straight_line" | "verified_endpoint_route" | "verified_single_endpoint" | "approximate_area_centroid" | "human_verified_override" | "unresolved";
export interface GeometryResolution {
  method: GeometryMethod;
  isApproximation: boolean;
  featureIds?: Array<string>;
  warnings?: Array<string>;
}
export interface Metadata {
  schemaVersion?: string;
  fixture?: boolean;
  distanceUnit?: string;
  thresholdsKm: Record<string, unknown>;
  utilityColors: Record<string, unknown>;
}
export interface Point {
  lat: number;
  lon: number;
}
export type Priority = "HIGH" | "MEDIUM" | "LOW";
export interface Project {
  id: string;
  utility: string;
  projectName: string;
  projectType: ProjectType;
  sponsor?: string | null;
  description?: string | null;
  voltageKv?: Array<number>;
  endpoints?: Array<Endpoint>;
  endpointStatus?: EndpointStatus;
  status?: string | null;
  plannedInServiceDate?: string | null;
  filedStartDate?: string | null;
  constructionWindow?: ConstructionWindow | null;
  estimatedCostUsd?: number | null;
  source: SourceRef;
  geometry?: Record<string, unknown> | null;
  geometryResolution?: GeometryResolution | null;
  evidence?: Evidence | null;
  warnings?: Array<string>;
}
export type ProjectType = "transmission_line" | "substation" | "reactor" | "other";
export interface Relationship {
  id: string;
  projectA: string;
  projectB: string;
  distanceKm: number;
  closestPoints: Array<unknown>;
  spatialTier: SpatialTier;
  timeline: Timeline;
  opportunityPriority: Priority;
  coordinationPlaybook?: Array<string>;
  evidence: Evidence;
}
export interface SourceRef {
  document: string;
  projectIdRaw: string;
  page: number;
  rawText?: string | null;
  rawFields?: Record<string, unknown>;
}
export type SpatialTier = "CROSSING" | "SHARED_CORRIDOR" | "SITE_LOGISTICS" | "CREWS_EQUIPMENT";
export interface Timeline {
  type: TimelineType;
  gapDays?: number | null;
  relevance: TimelineRelevance;
  isdWithinFiledSpan?: boolean;
}
export type TimelineRelevance = "OVERLAPPING" | "STRONG" | "MEANINGFUL" | "POSSIBLE" | "WEAK" | "UNKNOWN";
export type TimelineType = "IN_SERVICE_GAP" | "WINDOW_OVERLAP" | "UNRESOLVED";
export interface Zone {
  id: string;
  name: string;
  projectIds?: Array<string>;
  relationshipIds?: Array<string>;
  utilities?: Array<string>;
  closestDistanceKm: number;
  opportunityPriority: Priority;
  evidenceLevel: EvidenceLevel;
  coordinationThemes?: Array<string>;
  bounds: Bounds;
}
export interface Payload {
  metadata: Metadata;
  projects?: Array<Project>;
  relationships?: Array<Relationship>;
  zones?: Array<Zone>;
}

export type GridlockPayload = Payload;
